gud: EDID and mode object fixes
notro/gud-pico pull request #8
Opened 2024-09-21 22:53 UTC by kennylevinsen

The currently reported EDID fails validation, and does not match the mode object. The mode object on the other hand reports a pixel clock of 1, leading to a reported preferred refresh rate of 13mHz for my test.

Unify timing handling, fix the EDID validity by adding chromaticity and fixing up pixel format reporting, and add a few missing fields while at it. See the individual commits.

2024-10-03 18:14 UTC, notro commented
Thanks for taking the time to fix this. When I wrote the code I had never looked at edid before so it was highly likely that there were bugs. I haven't looked at it since either so I just assume you know what you're doing here :)

I have just a couple of nits that I have commented on.

Thanks for splitting it up instead of just dumping one single patch having all the changes.

2024-10-03 18:57 UTC, kennylevinsen commented
Hmm, I don't see any comments - is it perhaps a still-pending review or did github drop the ball on us?

2024-10-03 20:41 UTC, notro requested changes

2024-10-03 20:41 UTC, notro commented on libraries/gud_pico/gud.c
> +    uint32_t clock_khz = (disp->width + hblank) * (disp->height + vblank) * timings->framerate;
This is hz now and not khz, right?

2024-10-03 20:41 UTC, notro commented on libraries/gud_pico/gud.c
>      // EDID version 1.3
Comment needs updating too

2024-10-03 20:41 UTC, notro commented on libraries/gud_pico/gud.c
> +    edid[24] = 0x02; // RGB 4:4:4, preferred timings include pixel format and refresh rat
rat -> rate

2024-10-03 20:42 UTC, notro commented
> Hmm, I don't see any comments - is it perhaps a still-pending review

Indeed, I didn't know that I had to apply it..., never done a github review before

2024-10-04 09:09 UTC, kennylevinsen commented
> Indeed, I didn't know that I had to apply it...

On one hand it's nice that review comments are submitted in bulk for email reasons, on the other hand I sometimes get distracted or otherwise forget clicking submit, and then wonder why no one is reacting to my review... Hence why it was my first guess.

> Thanks for taking the time to fix this. When I wrote the code I had never looked at edid before so it was highly likely that there were bugs. I haven't looked at it since either so I just assume you know what you're doing here :)

Well, I did my best with respect to reading the spec, but libdisplay-info's `di-edid-decode` held my hand quite a bit through the process whenever I miscounted the bitfields. :)

Before:
```
$ di-edid-decode /sys/class/drm/card2-USB-1/edid
Block 0, Base EDID:
  EDID Structure Version & Revision: 1.3
  Vendor & Product Identification:
    Manufacturer: PIM
    Model: 1
    Serial Number: 437751487 (0x1a178ebf)
    Made in: week 1 of 2024
  Basic Display Parameters & Features:
    Digital display
    Maximum image size: 6 cm x 5 cm
    Gamma: 1.00
    RGB color display
    First detailed timing is the preferred timing
  Color Characteristics:
    Red  : 0.0000, 0.0000
    Green: 0.0000, 0.0000
    Blue : 0.0000, 0.0000
    White: 0.0000, 0.0000
  Established Timings I & II: none
  Standard Timings: none
  Detailed Timing Descriptors:
    DTD 1:   320x240    60.026042 Hz   4:3     14.406 kHz      4.610000 MHz (57 mm x 43 mm)
                 Hfront    0 Hsync   1 Hback   -1 Hpol P
                 Vfront    0 Vsync   1 Vback   -1 Vpol P
    Display Product Name: 'pico display'
Checksum: 0xf4

----------------

Failures:

Block 0, Base EDID:
  White-point coordinates are unset.
EDID conformity: FAIL
```

After:
```
$ di-edid-decode /sys/class/drm/card2-USB-1/edid
Block 0, Base EDID:
  EDID Structure Version & Revision: 1.4
  Vendor & Product Identification:
    Manufacturer: PIM
    Model: 1
    Serial Number: 437751487 (0x1a178ebf)
    Made in: week 38 of 2024
  Basic Display Parameters & Features:
    Digital display
    Bits per primary color channel: 6
    Digital interface is not defined
    Maximum image size: 6 cm x 5 cm
    Gamma: 2.20
    Supported color formats: RGB 4:4:4
    Default (sRGB) color space is primary color space
    First detailed timing includes the native pixel format and preferred refresh rate
  Color Characteristics:
    Red  : 0.6396, 0.3300
    Green: 0.2998, 0.5996
    Blue : 0.1503, 0.0595
    White: 0.3125, 0.3291
  Established Timings I & II: none
  Standard Timings: none
  Detailed Timing Descriptors:
    DTD 1:   320x240    60.026042 Hz   4:3     14.406 kHz      4.610000 MHz (57 mm x 43 mm)
                 Hfront    0 Hsync   0 Hback    0 Hpol P
                 Vfront    0 Vsync   0 Vback    0 Vpol P
    Display Product Name: 'pico display'
Checksum: 0x18

----------------

EDID conformity: PASS
```

Plus, the KMS object refresh rate now matches.

Before:
```
00:28:44.088 [INFO] [wlr] [backend/drm/drm.c:1586] Detected modes:
00:28:44.088 [INFO] [wlr] [backend/drm/drm.c:1616]   320x240 @ 0.013 Hz (preferred)
00:28:44.088 [INFO] [wlr] [backend/drm/drm.c:1636] Physical size: 60x50
```

After:
```
00:29:29.929 [INFO] [wlr] [backend/drm/drm.c:1586] Detected modes:
00:29:29.929 [INFO] [wlr] [backend/drm/drm.c:1616]   320x240 @ 60000.000 Hz (preferred)
00:29:29.929 [INFO] [wlr] [backend/drm/drm.c:1636] Physical size: 60x50
```

2024-10-04 09:09 UTC, kennylevinsen commented on libraries/gud_pico/gud.c
> +    uint32_t clock_khz = (disp->width + hblank) * (disp->height + vblank) * timings->framerate;
Ah, true.

2024-10-04 17:14 UTC, notro approved these changes

2024-10-04 17:16 UTC, merged